title: CROCOVAL project
description: CROss-modal registration in COrrelative Microscopies for VALvulopathy physiological characterisation
show_downloads: true
twitter_username: perrinepgil
title_image: /assets/images/logoCrocoval.png
post_author: Perrine Paul-Gilloteaux
image_path: /assets/images
url: "https://anrcrocoval.github.io"

plugins:
  - jekyll-latex
  - jekyll-target-blank

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
   toc_levels: 1..2

exclude: [vendor]
